// <auto-generated />
using System;
using InterventionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterventionAPI.Migrations
{
    [DbContext(typeof(InterventionAPIContext))]
    [Migration("20251227185739_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterventionAPI.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientAdresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientNom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionServices")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("En attente");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("DateFacture");

                    b.HasIndex("InterventionId")
                        .IsUnique();

                    b.HasIndex("NumeroFacture")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.ToTable("Factures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientAdresse = "Tunis, Tunisie",
                            ClientEmail = "mohamed@example.com",
                            ClientNom = "Mohamed Ben Ali",
                            DateFacture = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePaiement = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionServices = "Réparation robinet thermostatique - Remplacement joint",
                            InterventionId = 1,
                            ModePaiement = "Virement",
                            MontantHT = 60.50m,
                            NumeroFacture = "FACT-2024-001",
                            Statut = "Payée",
                            TVA = 0.19m
                        });
                });

            modelBuilder.Entity("InterventionAPI.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CoutMainOeuvre")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CoutPieces")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIntervention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EstGratuite")
                        .HasColumnType("bit");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReclamationId")
                        .HasColumnType("int");

                    b.Property<string>("SolutionApportee")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Planifiée");

                    b.Property<int>("TechnicienId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicienNom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DateIntervention");

                    b.HasIndex("EstGratuite");

                    b.HasIndex("ReclamationId");

                    b.HasIndex("Statut");

                    b.HasIndex("TechnicienId");

                    b.ToTable("Interventions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoutMainOeuvre = 45.00m,
                            CoutPieces = 15.50m,
                            DateFin = new DateTime(2024, 1, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            DateIntervention = new DateTime(2024, 1, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intervention pour réparer un robinet qui fuit",
                            EstGratuite = false,
                            Observations = "Joint usé à remplacer",
                            ReclamationId = 1,
                            SolutionApportee = "Remplacement du joint défectueux",
                            Statut = "Terminée",
                            TechnicienId = 101,
                            TechnicienNom = "Jean Dupont"
                        },
                        new
                        {
                            Id = 2,
                            DateIntervention = new DateTime(2024, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diagnostic du radiateur",
                            EstGratuite = true,
                            Observations = "",
                            ReclamationId = 2,
                            SolutionApportee = "",
                            Statut = "Planifiée",
                            TechnicienId = 102,
                            TechnicienNom = "Marie Martin"
                        });
                });

            modelBuilder.Entity("InterventionAPI.Models.Technicien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Competences")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Disponibilite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Disponible");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Zone")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Disponibilite");

                    b.HasIndex("Email");

                    b.HasIndex("UserId");

                    b.ToTable("Techniciens");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DateCreation = new DateTime(2025, 12, 27, 18, 57, 38, 243, DateTimeKind.Utc).AddTicks(6307),
                            DateMaj = new DateTime(2025, 12, 27, 18, 57, 38, 243, DateTimeKind.Utc).AddTicks(6308),
                            Disponibilite = "Disponible",
                            Email = "jean.dupont@example.com",
                            IsActif = true,
                            Nom = "Jean Dupont",
                            Telephone = "0102030405",
                            Zone = "Nord"
                        },
                        new
                        {
                            Id = 102,
                            DateCreation = new DateTime(2025, 12, 27, 18, 57, 38, 243, DateTimeKind.Utc).AddTicks(6310),
                            DateMaj = new DateTime(2025, 12, 27, 18, 57, 38, 243, DateTimeKind.Utc).AddTicks(6311),
                            Disponibilite = "Disponible",
                            Email = "marie.martin@example.com",
                            IsActif = true,
                            Nom = "Marie Martin",
                            Telephone = "0607080910",
                            Zone = "Sud"
                        });
                });

            modelBuilder.Entity("InterventionAPI.Models.Facture", b =>
                {
                    b.HasOne("InterventionAPI.Models.Intervention", "Intervention")
                        .WithOne("Facture")
                        .HasForeignKey("InterventionAPI.Models.Facture", "InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("InterventionAPI.Models.Intervention", b =>
                {
                    b.Navigation("Facture");
                });
#pragma warning restore 612, 618
        }
    }
}
