// <auto-generated />
using System;
using ArticleAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticleAPI.Migrations
{
    [DbContext(typeof(ArticleAPIContext))]
    [Migration("20251202184008_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleAPI.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DureeGarantieMois")
                        .HasColumnType("int");

                    b.Property<bool>("EstEnStock")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAchat = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Robinet thermostatique pour salle de bain",
                            DureeGarantieMois = 24,
                            EstEnStock = true,
                            Nom = "Robinet thermostatique",
                            PrixAchat = 89.99m,
                            Reference = "SAN-001",
                            Type = "Sanitaire"
                        },
                        new
                        {
                            Id = 2,
                            DateAchat = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Radiateur en aluminium 1500W",
                            DureeGarantieMois = 36,
                            EstEnStock = true,
                            Nom = "Radiateur à eau chaude",
                            PrixAchat = 249.99m,
                            Reference = "CHAU-001",
                            Type = "Chauffage"
                        },
                        new
                        {
                            Id = 3,
                            DateAchat = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "WC suspendu avec réservoir encastré",
                            DureeGarantieMois = 24,
                            EstEnStock = false,
                            Nom = "WC suspendu",
                            PrixAchat = 459.99m,
                            Reference = "SAN-002",
                            Type = "Sanitaire"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
