// <auto-generated />
using System;
using ClientAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientAPI.Migrations
{
    [DbContext(typeof(ClientAPIContext))]
    [Migration("20251217141732_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientAPI.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Tunis, Tunisie",
                            DateInscription = new DateTime(2025, 12, 17, 15, 17, 31, 805, DateTimeKind.Local).AddTicks(8269),
                            Email = "mohamed@example.com",
                            Nom = "Mohamed Ben Ali",
                            Telephone = "12345678"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Sousse, Tunisie",
                            DateInscription = new DateTime(2025, 12, 17, 15, 17, 31, 805, DateTimeKind.Local).AddTicks(8334),
                            Email = "fatma@example.com",
                            Nom = "Fatma Ahmed",
                            Telephone = "87654321"
                        });
                });

            modelBuilder.Entity("ClientAPI.Models.Reclamation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhotosUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("En attente");

                    b.Property<string>("TypeProbleme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DateCreation");

                    b.HasIndex("Statut");

                    b.ToTable("Reclamations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            ClientId = 1,
                            DateCreation = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Robinet qui fuit dans la salle de bain",
                            Priorite = "Moyenne",
                            Statut = "En cours",
                            TypeProbleme = "Général"
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            ClientId = 2,
                            DateCreation = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Radiateur ne chauffe pas correctement",
                            Priorite = "Moyenne",
                            Statut = "En attente",
                            TypeProbleme = "Général"
                        });
                });

            modelBuilder.Entity("ClientAPI.Models.ReclamationPiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Fournie")
                        .HasColumnType("bit");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("ReclamationId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReclamationId");

                    b.ToTable("ReclamationPiece");
                });

            modelBuilder.Entity("ClientAPI.Models.Reclamation", b =>
                {
                    b.HasOne("ClientAPI.Models.Client", "Client")
                        .WithMany("Reclamations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ClientAPI.Models.ReclamationPiece", b =>
                {
                    b.HasOne("ClientAPI.Models.Reclamation", null)
                        .WithMany("PiecesNecessaires")
                        .HasForeignKey("ReclamationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientAPI.Models.Client", b =>
                {
                    b.Navigation("Reclamations");
                });

            modelBuilder.Entity("ClientAPI.Models.Reclamation", b =>
                {
                    b.Navigation("PiecesNecessaires");
                });
#pragma warning restore 612, 618
        }
    }
}
